### ISSUE TITLE
Collect Standings from Location GC

### ISSUE THREAD

**Issue by civrot** [PuzzledPint/puzzledpint.com#55]
## Input Form

I imagined that we would update the edit events_location page ( http://beta.puzzledpint.com/game_control/events/5/event_locations/6/edit ) by adding a tab called Standings, where location GC could enter in the information. The standings view would contain a dynamic form where location GC could enter multiple rows of data, one for each team.
## Standings Table

``` ruby
    create_table :team_standings do |t|
      t.references :event_id, null: false
      t.string :team_name, null: false
      t.integer :team_size, null: false, default: 0
      t.time :start_time
      t.time :end_time
      t.integer :puzzles_solved, null: false, default: 0
    end
```

**Comment by BrianEnigma** [comment]
1. Is it worth importing existing standings?
2. Do we want a GC boolean, to help track overall event attendance?
3. How about a freeform string field for QotM response?

**Comment by zyrain** [comment]
0. Why is this marked "ready"?
1. Yes.  This shouldn't be a problem.  I already have written code to pull from our google docs into a database.  (written for my blog post analysis)
2. Probably mark it in a separate place, not a row as it is now.  Possibly by adding specific GC users to each month to track not only numerical GC attendance, but actual per user attendance.
3. We can, but QotM parsing is also an issue, so I'd like to standardize somehow.  Ideally with custom validation code per month, so we set the parameters and they have to input it (string by default).  though in the interim  we can force single-integer input (which will handle most recent months, as we ask for numbers since they're more easily aggregated).
